/**
 * Copyright © 2025-2026 Wenze Wei. All Rights Reserved.
 *
 * AUTO-GENERATED by build.py — DO NOT EDIT BY HAND.
 * Re-generated on every build with the requested locale subset.
 */

import type { LocaleMessages } from "../features/i18n.js";
import { zh } from "./zh.js";
import { en } from "./en.js";
import { zhHant } from "./zh-Hant.js";
import { ja } from "./ja.js";
import { ko } from "./ko.js";
import { de } from "./de.js";
import { es } from "./es.js";
import { pt } from "./pt.js";
import { tr } from "./tr.js";
import { ar } from "./ar.js";
import { he } from "./he.js";

export const LOCALE_REGISTRY = {
  zh: zh,
  en: en,
  zh-Hant: zhHant,
  ja: ja,
  ko: ko,
  de: de,
  es: es,
  pt: pt,
  tr: tr,
  ar: ar,
  he: he,
} as const satisfies Record<string, LocaleMessages>;

export const ALL_LOCALES: readonly string[] = ['zh', 'en', 'zh-Hant', 'ja', 'ko', 'de', 'es', 'pt', 'tr', 'ar', 'he'];
