#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Copyright © 2025-2026 Wenze Wei. All Rights Reserved.
#
# This file is part of Encre.
# The Encre project belongs to the Dunimd Team.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# DISCLAIMER: Users must comply with applicable AI regulations.
# Non-compliance may result in service termination or legal liability.

from __future__ import annotations

"""
Inspired by the Hermes Agent project (https://github.com/NousResearch/hermes-agent.git).
Thanks to Hermes Agent for the inspiration on this module.

AES-256-GCM utilities for QQBot QR-code credential decryption.

This module provides two functions used in the scan-to-configure onboard flow:

1. :func:`generate_bind_key` — generates a random 256-bit AES key, returned as
   base64. The key is sent to ``create_bind_task`` so the server can encrypt
   the bot's *client_secret* before returning it. Only the CLI process holds
   the key, ensuring the secret never travels in plaintext.

2. :func:`decrypt_secret` — decrypts the ``bot_encrypt_secret`` value from
   ``poll_bind_result`` using AES-256-GCM with the bind key.

Ciphertext layout (after base64-decoding the encrypted value)::

    IV (12 bytes) ‖ ciphertext (N bytes) ‖ AuthTag (16 bytes)

The ``cryptography`` library's :class:`~cryptography.hazmat.primitives.ciphers.aead.AESGCM`
is used. The IV and ciphertext+tag are extracted from the raw bytes and passed
to ``aesgcm.decrypt(iv, ciphertext_with_tag, None)``.

Dependencies:
    - ``cryptography`` — installed as a dependency of the qqbot platform.
      If unavailable, ``decrypt_secret`` will raise ImportError.
"""

import base64
import os


def generate_bind_key() -> str:
    """Generate a 256-bit random AES key and return it as base64.

    This key is used to encrypt/decrypt the bot's client_secret during the
    QR-code scan-to-configure flow. It is generated locally, sent to the
    QQ server via ``create_bind_task``, and then used to decrypt the
    response from ``poll_bind_result``.

    Security:
        Uses ``os.urandom(32)`` which draws from the OS CSPRNG. The key
        is never stored — only held in memory during the registration session.

    Returns:
        Base64-encoded 32-byte AES-256 key (44 characters).

    Example::

        >>> key = generate_bind_key()
        >>> len(key)
        44
    """
    return base64.b64encode(os.urandom(32)).decode()


def decrypt_secret(encrypted_base64: str, key_base64: str) -> str:
    """Decrypt a base64-encoded AES-256-GCM ciphertext.

    Used to decrypt the ``bot_encrypt_secret`` returned by
    ``poll_bind_result`` during QR-code onboard. The ciphertext contains
    the bot's client_secret encrypted with the bind key generated by
    :func:`generate_bind_key`.

    Ciphertext layout (after base64-decoding)::

        IV (12 bytes) ‖ ciphertext (N bytes) ‖ AuthTag (16 bytes)

    The AES-GCM mode authenticates the ciphertext — if the key is wrong or
    the data is tampered with, ``decrypt()`` raises an
    :class:`~cryptography.exceptions.InvalidTag` exception.

    Args:
        encrypted_base64: The ``bot_encrypt_secret`` value from
            ``poll_bind_result`` API response. Already base64-encoded.
        key_base64: The base64 AES-256 key generated by
            :func:`generate_bind_key`. Must match the key used for encryption.

    Returns:
        The decrypted *client_secret* as a UTF-8 string.

    Raises:
        cryptography.exceptions.InvalidTag: If the authentication tag doesn't
            match (wrong key or tampered data).
        ValueError: If the base64 input is malformed.
    """
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM

    # Decode base64 inputs to raw bytes.
    key = base64.b64decode(key_base64)
    raw = base64.b64decode(encrypted_base64)

    # Extract IV (first 12 bytes) and ciphertext+auth_tag (remaining bytes).
    # AESGCM.decrypt expects ciphertext and auth_tag concatenated.
    iv = raw[:12]
    ciphertext_with_tag = raw[12:]  # AESGCM expects ciphertext + tag concatenated

    # Create AESGCM instance and decrypt.
    aesgcm = AESGCM(key)
    plaintext = aesgcm.decrypt(iv, ciphertext_with_tag, None)
    return plaintext.decode("utf-8")
